AjaxDjango/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('enroll.urls')),
]

enroll/urls.py
from enroll import views
from django.urls import path

app_name = "enroll"

urlpatterns = [
    path('', views.home, name='home'),
    path('fetch_data/', views.fetch_data, name='fetch_data'),
    path('save/', views.save_data, name='save'),
    path('edit/', views.edit_data, name='edit'),
    path('delete/', views.delete_data, name='delete'),
]

enroll/models.py
from django.db import models

# Create your models here.


class User(models.Model):
    name = models.CharField(max_length=70)
    email = models.CharField(max_length=100)
    password = models.CharField(max_length=100)

    # class Meta:
    #     ordering = ['-name']

enroll/forms.py
from django import forms
from .models import User


class StudentRegistration(forms.ModelForm):
    class Meta:
        model = User
        fields = ['name', 'email', 'password']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'id': 'nameid'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'id': 'emailid'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control', 'id': 'passwordid'})
        }

enroll/views.py
from django.shortcuts import render
# from AjaxDjango.enroll.models import User
from .forms import StudentRegistration
from .models import User
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt    # To remove(exclude) csrf_token 
from django.contrib.auth.hashers import make_password
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
# Create your views here.

def home(request):
    form = StudentRegistration()
    return render (request, 'home.html', {
        'form':form})

# from django.db import connection
def fetch_data(request):
    # cursor = connection.cursor()
    # cursor.execute("SELECT * FROM enroll_user ORDER BY id")
    # student_data = cursor.fetchall()

    student_data = User.objects.all().values().order_by('id')
    paginator = Paginator(student_data, 5)  # Show 5 records per page

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    student_data = list(page_obj)  # Convert the queryset to a list

    return JsonResponse({'student_data': student_data, 'total_pages': paginator.num_pages})

# def fetch_data(request):
#     student_data = list(User.objects.values())
#     return JsonResponse({'student_data': student_data})


def save_data(request):
    if request.method == "POST":
        form = StudentRegistration(request.POST)
        # print(form.data)
        if form.is_valid():
            sid = request.POST.get('stuid')   # FOR UPDATE DATA
            name = request.POST['name']
            email = request.POST['email']
            password = request.POST['password']
            
            # Encrypt the password
            # password = make_password(password)

            if(sid == ''):
                usr = User(name=name, email=email,password=password)
            else:
                usr = User(id=sid, name=name, email=email,password=password)
            
            usr.save()
            # stud = User.objects.values()
            # student_data = list(stud)
            # print(student_data)
            return JsonResponse({'status' : 'Save'})
        else:
            return JsonResponse({'status':  0})

def delete_data(request):
    if request.method == "POST":
        id = request.POST.get('sid')
        # print(id)
        pi = User.objects.get(pk=id)
        pi.delete()
        return JsonResponse({'status' : 1})
    else:
        return JsonResponse({'status': 0})


def edit_data(request):
    if request.method == "GET":
        id = request.GET.get('sid')
        # print(id)
        student = User.objects.get(pk=id)
        student_data = {"id":student.id, "name" : student.name, "email": student.email, "password": student.password}
        return JsonResponse(student_data)
    if request.method == "POST":
        form = StudentRegistration(request.POST)
        if form.is_valid():
            sid = request.POST.get('stuid')   # FOR UPDATE DATA
            name = request.POST['name']
            email = request.POST['email']
            password = request.POST['password']
            
            usr = User(id=sid, name=name, email=email,password=password)
            usr.save()
            stud = User.objects.filter(id = sid).values()
            student_data = list(stud)
            return JsonResponse({'status' : 'Updated', 'student_data': student_data})
        else:
            return JsonResponse({'status':  0})    

enroll/templates/ajax.html
<script>
  var selectedPageNumber = 1


  function hideModal() {
    $('#exampleModal').modal('hide');
  }

  $(document).ready(function() {
    $('#exampleModal').on('hidden.bs.modal', function (e) {
      // Reset the form elements when the modal is hidden
      $(this).find('form')[0].reset();
      $("#btnupdate").hide();
      $("#btnsave").show();
    });
  });

  // ADD DATA
  $("#btnsave").click(function () {
    output = "";
    let sid = $("#stuid").val(); // This is for EDIT DATA
    let nm = $("#nameid").val();
    let em = $("#emailid").val();
    let pw = $("#passwordid").val();
    let csr = $("input[name = csrfmiddlewaretoken]").val();
    if (nm == "") {
      console.log("Please Enter Name");
    } else if (em == "") {
      console.log("Please Enter Email");
    } else if (pw == "") {
      console.log("Please Enter Password");
    } else {
      mydata = {
        stuid: sid,
        name: nm,
        email: em,
        password: pw,
        csrfmiddlewaretoken: csr,
      };
      $.ajax({
        url: "{% url 'enroll:save' %}",
        method: "POST",
        data: mydata,
        success: function (data) {
          x = data.student_data;
          if (data.status == "Save") {
            $("#msg").removeClass("alert-danger")
            $("#msg").addClass("alert-primary")
            $("#msg").text("From Submitted Seccessfully");
            $("#msg").show();
            $("#msg").delay(3000).fadeOut();
            hideModal();
            $('#successToast').toast('show');

            fetchData(selectedPageNumber)

            for (i = 0; i < x.length; i++) {
              output +=
              `<tr>
                <td>${x[i].id}</td>
                <td>${x[i].name}</td>
                <td>${x[i].email}</td>
                <td>${x[i].password}</td>
                <td>
                    <input type="button" data-sid="${x[i].id}" class="btn btn-warning tn-sm btn-edit" value="Edit" />
                    <input type="button" data-sid="${x[i].id}" class="btn btn-danger tn-sm btn-del" value="Delete" />
                </td>
              </tr>`;
            }
            // document.getElementById('tbody').innerHTML = output
            // $("#tbody").html(output);

            $("#stuid").val("");
            $("form")[0].reset();
          }
          if (data.status == 0) {
            $("#msg").removeClass("alert-primary")
            $("#msg").addClass("alert-danger")
            $("#msg").text("Unable to Save Data");
            $("#msg").show();
            $("#stuid").val("");
            $("form")[0].reset();
          }
        },
      });
    }
  });

  
  // DELETE DATA
  $("tbody").on("click", ".btn-del", function () {
    let id = $(this).attr("data-sid");
    let csr = $("input[name = csrfmiddlewaretoken]").val();

    mydata = { sid: id, csrfmiddlewaretoken: csr };
    mythis = this;
    $.ajax({
      url: "{% url 'enroll:delete' %}",
      method: "POST",
      data: mydata,
      success: function (data) {

        if (data.status == 1) {
          $("#msg").addClass("alert-danger")
          $("#msg").text("Data Deleted Successfully");
          $("#msg").show();
          $(mythis).closest("tr").fadeOut();
          $("#msg").delay(3000).fadeOut();
        }
        if (data.status == 0) {
          $("#msg").addClass("alert-danger")
          $("#msg").text("Unable to Delete Data");
          $("#msg").show();
        }
      },
    });
  });

  
  // EDIT Data
  $("tbody").on("click", ".btn-edit", function () {

    let id = $(this).attr("data-sid");
    let csr = $("input[name = csrfmiddlewaretoken]").val();
    mydata = { sid: id };
    mythis = this;
    $.ajax({
      url: "{% url 'enroll:edit' %}",
      method: "GET",
      data: mydata,
      success: function (data) {
        $('#exampleModal').modal('show');
        $("#btnsave").hide();
        $("#btnupdate").show();
        $("#stuid").val(data.id);
        $("#nameid").val(data.name);
        $("#emailid").val(data.email);
        $("#passwordid").val(data.password);
      },
    });
  });

  // Handle Edit 
  $("#btnupdate").click(function () {
    output = "";
    let sid = $("#stuid").val(); // This is for EDIT DATA
    let nm = $("#nameid").val();
    let em = $("#emailid").val();
    let pw = $("#passwordid").val();
    let csr = $("input[name = csrfmiddlewaretoken]").val();
    if (nm == "") {
      console.log("Please Enter Name");
    } else if (em == "") {
      console.log("Please Enter Email");
    } else if (pw == "") {
      console.log("Please Enter Password");
    } else {
      mydata = {
        stuid: sid,
        name: nm,
        email: em,
        password: pw,
        csrfmiddlewaretoken: csr,
      };
      $.ajax({
        url: "{% url 'enroll:edit' %}",
        method: "POST",
        data: mydata,
        success: function (data) {

          if (data.status == "Updated") {
            $("#msg").removeClass("alert-danger")
            $("#msg").addClass("alert-primary")
            $("#msg").text("From Submitted Seccessfully");
            $("#msg").show();
            $("#msg").delay(3000).fadeOut();
            hideModal();

            st = data.student_data[0];
            var updatedRow =
                  `<tr id="row-${st.id}">
                    <td>${st.id}</td>
                    <td>${st.name}</td>
                    <td>${st.email}</td>
                    <td>${st.password}</td>
                    <td>
                        <input type="button" data-sid="${st.id}" class="btn btn-warning tn-sm btn-edit"
                            value="Edit" />
                        <input type="button" data-sid="${st.id}" class="btn btn-danger tn-sm btn-del"
                            value="Delete" />
                    </td>
                  </tr>`;
            let selectedRow = $(`#row-${st.id}`).closest("tr").replaceWith(updatedRow);
            
            $("#stuid").val("");
            $("form")[0].reset();
          }
          if (data.status == 0) {
            $("#msg").removeClass("alert-primary")
            $("#msg").addClass("alert-danger")
            $("#msg").text("Unable to Save Data");
            $("#msg").show();
            $("#stuid").val("");
            $("form")[0].reset();
          }

        }
      })
    }
  });

  //$("#msg").delay(5000).slideUp(200, function () {
  //  $(this).alert('close');
  //});

                  // updated
  function fetchData(page) {
      var tbody = $('#tbody');
      tbody.empty();
      $('.lds-spinner').show();

      $.ajax({
                        // updated
          url: '/fetch_data/?page=' + page,  // Replace with the URL to fetch the data from the server
          type: 'GET',
          dataType: 'json',
          success: function(response) {
              var studentData = response.student_data;

              studentData.forEach(function(st){ 
                var row = 
                `<tr id="row-${st.id}">
                  <td>${st.id}</td>
                  <td>${st.name}</td>
                  <td>${st.email}</td>
                  <td>${st.password}</td>
                  <td>
                      <input type="button" data-sid="${st.id}" class="btn btn-warning tn-sm btn-edit"
                          value="Edit" />
                      <input type="button" data-sid="${st.id}" class="btn btn-danger tn-sm btn-del"
                          value="Delete" />
                  </td>
                </tr>`;
                tbody.append(row);
                // updated
                updatePagination(page, response.total_pages);
              })


              $('.lds-spinner').hide();

          },
          error: function(xhr, status, error) {
              console.log(error);
              $('#table-container #loader').hide();
          }
      });
  }
  // updated
  fetchData(1);
</script>

<script>
  $(document).ready(function() {
    $('#pagination-container').on('click', '.page-link', function(event) {
        event.preventDefault();
        var page = $(this).text(); 
        selectedPageNumber = page
        fetchData(page);
    });
});


function updatePagination(currentPage, totalPages) {
  currentPage = parseInt(currentPage)
  var paginationContainer = $('.pagination');
  paginationContainer.empty();

  var pageRange = 2;  // Number of pages to show before and after the current page

  var startPage = Math.max(1, currentPage - pageRange);
  var endPage = Math.min(totalPages, currentPage + pageRange);

  // Add page links
  for (var i = startPage; i <= endPage; i++) {
      var pageLink = '<li class="page-item';
      if (i === currentPage) {
          pageLink += ' active';
      }
      pageLink += '"><a class="page-link" href="#">' + i + '</a></li>';
      paginationContainer.append(pageLink);
  }

}
</script>

enroll/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" />
  <!-- <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" /> -->
  <link rel="stylesheet" href="{% static 'css/custom.css' %}" />
  <title>Django Ajax CRUD</title>
  <style>

  </style>
</head>

<body>
  <div class="container mt-5">
    <h2 class="text-center alert alert-danger">
      Django Ajax bootstrap CRUD Project
    </h2>


    <div class="toast" id="successToast" role="alert" aria-live="assertive" aria-atomic="true" data-delay="3000"
      style="position: absolute; top: 20px; right: 20px;">
      <div class="toast-header bg-success text-white">
        <strong class="me-auto">Success</strong>
        <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
      </div>
      <div class="toast-body">
        Seccessfully done.
      </div>
    </div>


    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary mb-3" data-bs-toggle="modal" data-bs-target="#exampleModal">
      Add Student
    </button>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">Form</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <form method="POST">
              {% csrf_token %}
              <input type="hidden" name="stuid" id="stuid" />
              {{form.as_p}}
            </form>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="button" id="btnsave" class="btn btn-success">Save</button>
            <button type="button" id="btnupdate" class="btn btn-success" style="display: none;">Update</button>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <!-- <div class="col-sm-4"> -->
      <!-- <h4 class="text-center alert alert-info">Add/Update Student</h4>
                <form method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="stuid" id="stuid" />
                    {{form.as_p}}
                    <input type="button" value="Save" class="btn btn-success" id="btnsave" />
                </form>
                <br /> -->
      <!-- <div id="msg" class="alert" style="display: none"></div> -->
      <!-- </div> -->
      <div class="col">
        <h4 class="text-center alert alert-info">Show Student</h4>
        <div class="main-loader" id="main-loader">
          <table class="table table-hover">
            <thead>
              <tr>
                <th scope="col">ID</th>
                <th scope="col">Name</th>
                <th scope="col">Email</th>
                <th scope="col">Password</th>
                <th scope="col">Action</th>
              </tr>
            </thead>
            <tbody id="tbody">
              
            </tbody>
            <!-- <tbody id="tbody">
                        {% for st in stu %}
                        <tr>
                            <td>{{st.id}}</td>
                            <td>{{st.name}}</td>
                            <td>{{st.email}}</td>
                            <td>{{st.password}}</td>
                            <td>
                                <input type="button" data-sid="{{st.id}}" class="btn btn-warning tn-sm btn-edit"
                                    value="Edit" />
                                <input type="button" data-sid="{{st.id}}" class="btn btn-danger tn-sm btn-del"
                                    value="Delete" />
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody> -->
          </table>

          <div class="lds-spinner" style="margin-left: 50%;">
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
          </div>

          <!-- pagination -->
          <div class="container">
            <div id="pagination-container">
              <nav aria-label="Page navigation example">
                <ul class="pagination">
                
                </ul>
              </nav>
            </div>
          </div>


          


        </div>
      </div>
    </div>
  </div>
  <script src="{% static 'js/jquery.js' %}"></script>
  <script src="{% static 'js/popper.js' %}"></script>
  <script src="{% static 'js/bootstrap.js' %}"></script>
  {% include "ajax.html" %}
</body>

</html>